- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HR
    TRAINER: Sivakumar
  tasks:
  - name: print course information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
    #vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, course duration: {{ DURATION }}, Trainser is {{ TRAINER }}"

  - name: print course information again... notice COURSE Variable read from global
    ansible.builtin.debug:
    #vars reference should be surrounded by ""
      msg: "Hello {{ COURSE }}, course duration: {{ DURATION }}, Trainser is {{ TRAINER }}"